---
- name: copy config file(s)
  template:
    src: "{{ item }}.j2"
    dest: "/etc/unbound/unbound.conf.d/{{ item }}"
    mode: 0644
  with_items:
    - general.conf
    - forward_zone.conf
    - control.conf
  notify: restart unbound

- name: configure unbound zones
  template:
     src: zone.conf.j2
     dest: "/etc/unbound/unbound.conf.d/{{ item.name }}.conf"
     mode: 0644
  with_items: "{{ unbound_zones }}"
  notify: restart unbound
